# Site settings
title: Parhum Khoshbakht
email: parhum.kh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creative focus on simplicity and things that appear on screens
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://parhumm.github.io" #"http://parhum.net" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
permalink: /:categories/:title
exclude: ["node_modules", "assets/scss", "assets/vendor", "gulpfile.js", "package.json", "bower.json", "LICENSE", "Gemfile", "Gemfile.lock"]


# Menu Data
navigation:
- text: Home
  url: /
- text: Portfolio
  url: /portfolio/
- text: Blog
  url: /blog/


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: parhum.kh@gmail.com
  facebook:
  flickr:
  github: parhumm
  instagram: parhumm
  linkedin:
  pinterest:
  rss: RSS # just type anything here for a working RSS icon
  twitter: parhumm
  stackoverflow: "users/2907474/parhum" # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: parhumm